name: Build AMI Pipeline

on:
  workflow_dispatch:

jobs:
  build-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v3

      - name: Setup Ansible
        uses: ./.github/actions/setup-ansible

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug repo structure
        run: ls -R

      - name: Build AMI with Packer
        working-directory: packer
        run: |
          packer init .

          echo "Running build..."
          packer build ami.pkr.hcl | tee output.log

          echo "Extracting AMI..."
          AMI_ID=$(grep -o 'ami-[a-zA-Z0-9]*' output.log | tail -1)

          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
          echo "Baked AMI ID: $AMI_ID"

          if [ -z "$AMI_ID" ]; then
            echo "❌ AMI creation failed"
            exit 1
          fi

      - name: Show AMI ID
        run: echo "The baked AMI ID is $AMI_ID"
